"""multiple attendance records fixed

Revision ID: f2056cd6244a
Revises: 
Create Date: 2025-04-25 10:38:20.706814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2056cd6244a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Attendance', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_attendance', ['emp_id', 'date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Attendance', schema=None) as batch_op:
        batch_op.drop_constraint('unique_attendance', type_='unique')

    # ### end Alembic commands ###
